# Generated by Django 4.2 on 2024-09-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='año',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='revista',
            name='año',
            field=models.PositiveBigIntegerField(),
        ),
    ]
