from AppBiblioteca import views
from django.urls import path

urlpatterns = [
    path('inicio/', views.inicio, name='inicio'),
    path('libros/', views.libros, name='libros'),
    path('revistas/', views.revistas, name='revistas'),
    path('peliculas/', views.peliculas, name='peliculas'),
    path('libroFormulario/', views.libro_Formulario, name='libroFormulario'),
    path('revistaFormulario/', views.revista_Formulario, name='revistaFormulario'),
    path('peliculaFormulario/', views.pelicula_Formulario, name='peliculaFormulario'),
    path('busquedaDirector/', views.busqueda_Director, name='busquedaDirector'),
    path('buscar/', views.buscar, name='buscar'),
    path('leerLibros/', views.leerLibros, name='leerLibros'),
    path('eliminarLibro/<libro_nombre>/', views.eliminarLibro, name='eliminarLibro'),
    path('clases/librosList/', views.LibrosListView.as_view(), name='librosList'),
    path('clases/librosDetail/<str:nombre>/', views.LibrosDetailView.as_view(), name='librosDetail'),
    path('clases/newLibro/', views.LibroCreateView.as_view(), name='librosNew'),
    path('clases/updateLibro/<str:nombre>/', views.LibroUpdateView.as_view(), name='librosUpdate'),
    path('clases/deleteLibro/<str:nombre>/', views.LibroDeleteView.as_view(), name='librosDelete'),
    path('clases/revistasList/', views.RevistaListView.as_view(), name='revistasList'),
    path('clases/revistasDetail/<str:nombre>/', views.RevistaDetailView.as_view(), name='revistasDetail'),
    path('clases/newRevista/', views.RevistaCreateView.as_view(), name='RevistasNew'),
    path('clases/updateRevista/<str:nombre>/', views.RevistaUpdateView.as_view(), name='revistasUpdate'),
    path('clases/deleteRevista/<str:nombre>/', views.RevistaDeleteView.as_view(), name='revistasDelete'),
    path('clases/peliculasList/', views.PeliculaListView.as_view(), name='peliculasList'),
    path('clases/peliculasDetail/<str:nombre>/', views.PeliculaDetailView.as_view(), name='peliculasDetail'),
    path('clases/newPelicula/', views.PeliculaCreateView.as_view(), name='peliculasNew'),
    path('clases/updatePelicula/<str:nombre>/', views.PeliculaUpdateView.as_view(), name='peliculasUpdate'),
    path('clases/deletePelicula/<str:nombre>/', views.PeliculaDeleteView.as_view(), name='peliculasDelete'),
]